# CMake generated Testfile for 
# Source directory: /workspace/sample/test
# Build directory: /workspace/sample/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(StackTest.NewStackIsEmpty "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.NewStackIsEmpty")
set_tests_properties(StackTest.NewStackIsEmpty PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PushIncreasesSize "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PushIncreasesSize")
set_tests_properties(StackTest.PushIncreasesSize PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PeekReturnsTopWithoutRemoving "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PeekReturnsTopWithoutRemoving")
set_tests_properties(StackTest.PeekReturnsTopWithoutRemoving PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PopReturnsTopAndRemovesIt "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PopReturnsTopAndRemovesIt")
set_tests_properties(StackTest.PopReturnsTopAndRemovesIt PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PopOnEmptyThrows "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PopOnEmptyThrows")
set_tests_properties(StackTest.PopOnEmptyThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PeekOnEmptyThrows "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PeekOnEmptyThrows")
set_tests_properties(StackTest.PeekOnEmptyThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(StackTest.PushPopMultipleElements "/workspace/sample/test/StackTest" "--gtest_filter=StackTest.PushPopMultipleElements")
set_tests_properties(StackTest.PushPopMultipleElements PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;12;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.SingleNumber "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.SingleNumber")
set_tests_properties(TokenizerTest.SingleNumber PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.SimpleAddition "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.SimpleAddition")
set_tests_properties(TokenizerTest.SimpleAddition PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.AllOperators "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.AllOperators")
set_tests_properties(TokenizerTest.AllOperators PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.Parentheses "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.Parentheses")
set_tests_properties(TokenizerTest.Parentheses PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.MultiDigitNumber "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.MultiDigitNumber")
set_tests_properties(TokenizerTest.MultiDigitNumber PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.NoSpaces "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.NoSpaces")
set_tests_properties(TokenizerTest.NoSpaces PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.UnaryMinusAtStart "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.UnaryMinusAtStart")
set_tests_properties(TokenizerTest.UnaryMinusAtStart PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.UnaryMinusAfterLeftParen "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.UnaryMinusAfterLeftParen")
set_tests_properties(TokenizerTest.UnaryMinusAfterLeftParen PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.UnaryMinusAfterOperator "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.UnaryMinusAfterOperator")
set_tests_properties(TokenizerTest.UnaryMinusAfterOperator PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.InvalidCharacterThrows "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.InvalidCharacterThrows")
set_tests_properties(TokenizerTest.InvalidCharacterThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.EmptyExpression "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.EmptyExpression")
set_tests_properties(TokenizerTest.EmptyExpression PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.WhitespaceOnly "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.WhitespaceOnly")
set_tests_properties(TokenizerTest.WhitespaceOnly PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(TokenizerTest.NestedParentheses "/workspace/sample/test/TokenizerTest" "--gtest_filter=TokenizerTest.NestedParentheses")
set_tests_properties(TokenizerTest.NestedParentheses PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;16;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.SingleNumber "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.SingleNumber")
set_tests_properties(CalculatorTest.SingleNumber PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.Addition "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.Addition")
set_tests_properties(CalculatorTest.Addition PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.Subtraction "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.Subtraction")
set_tests_properties(CalculatorTest.Subtraction PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.Multiplication "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.Multiplication")
set_tests_properties(CalculatorTest.Multiplication PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.Division "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.Division")
set_tests_properties(CalculatorTest.Division PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MultiplicationBeforeAddition "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MultiplicationBeforeAddition")
set_tests_properties(CalculatorTest.MultiplicationBeforeAddition PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.DivisionBeforeSubtraction "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.DivisionBeforeSubtraction")
set_tests_properties(CalculatorTest.DivisionBeforeSubtraction PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MixedPrecedence "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MixedPrecedence")
set_tests_properties(CalculatorTest.MixedPrecedence PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.SamePrecedenceLeftToRight "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.SamePrecedenceLeftToRight")
set_tests_properties(CalculatorTest.SamePrecedenceLeftToRight PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MultipleDivisionsLeftToRight "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MultipleDivisionsLeftToRight")
set_tests_properties(CalculatorTest.MultipleDivisionsLeftToRight PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ParenthesesOverridePrecedence "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ParenthesesOverridePrecedence")
set_tests_properties(CalculatorTest.ParenthesesOverridePrecedence PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.NestedParentheses "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.NestedParentheses")
set_tests_properties(CalculatorTest.NestedParentheses PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ParenthesesWithinExpression "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ParenthesesWithinExpression")
set_tests_properties(CalculatorTest.ParenthesesWithinExpression PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.DeeplyNestedParentheses "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.DeeplyNestedParentheses")
set_tests_properties(CalculatorTest.DeeplyNestedParentheses PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.NegativeNumberAtStart "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.NegativeNumberAtStart")
set_tests_properties(CalculatorTest.NegativeNumberAtStart PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.NegativeNumberInParentheses "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.NegativeNumberInParentheses")
set_tests_properties(CalculatorTest.NegativeNumberInParentheses PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.NegativeMultiplied "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.NegativeMultiplied")
set_tests_properties(CalculatorTest.NegativeMultiplied PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ComplexExpression1 "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ComplexExpression1")
set_tests_properties(CalculatorTest.ComplexExpression1 PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ComplexExpression2 "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ComplexExpression2")
set_tests_properties(CalculatorTest.ComplexExpression2 PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ComplexExpression3 "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ComplexExpression3")
set_tests_properties(CalculatorTest.ComplexExpression3 PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.LargeChainedOperations "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.LargeChainedOperations")
set_tests_properties(CalculatorTest.LargeChainedOperations PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MixedAllOperators "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MixedAllOperators")
set_tests_properties(CalculatorTest.MixedAllOperators PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.ZeroOperations "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.ZeroOperations")
set_tests_properties(CalculatorTest.ZeroOperations PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MultiplyByZero "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MultiplyByZero")
set_tests_properties(CalculatorTest.MultiplyByZero PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.SubtractToNegative "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.SubtractToNegative")
set_tests_properties(CalculatorTest.SubtractToNegative PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.IntegerDivisionTruncates "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.IntegerDivisionTruncates")
set_tests_properties(CalculatorTest.IntegerDivisionTruncates PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.NoSpaces "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.NoSpaces")
set_tests_properties(CalculatorTest.NoSpaces PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.DivisionByZeroThrows "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.DivisionByZeroThrows")
set_tests_properties(CalculatorTest.DivisionByZeroThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.EmptyExpressionThrows "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.EmptyExpressionThrows")
set_tests_properties(CalculatorTest.EmptyExpressionThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MismatchedLeftParenThrows "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MismatchedLeftParenThrows")
set_tests_properties(CalculatorTest.MismatchedLeftParenThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.MismatchedRightParenThrows "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.MismatchedRightParenThrows")
set_tests_properties(CalculatorTest.MismatchedRightParenThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
add_test(CalculatorTest.InvalidCharacterThrows "/workspace/sample/test/CalculatorTest" "--gtest_filter=CalculatorTest.InvalidCharacterThrows")
set_tests_properties(CalculatorTest.InvalidCharacterThrows PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/workspace/sample/test/CMakeLists.txt;20;gtest_add_tests;/workspace/sample/test/CMakeLists.txt;0;")
subdirs("../_deps/googletest-build")
